Enable invokes customized methods
henrique-gouveia/DataQI.EntityFrameworkCore pull request #8
Opened 2021-10-10 14:35 UTC by henrique-gouveia

changed TEntity requirements on IEntityRepository interface

2021-10-31 13:28 UTC, ypedroo requested changes

2021-10-31 13:28 UTC, ypedroo commented on test/DataQI.EntityFrameworkCore.Test/Fixtures/DbFixture.cs
> +            // CustomerRepository = new EntityRepository<Customer, int>(Context);
Remove commented out code

2021-10-31 13:28 UTC, ypedroo commented on test/DataQI.EntityFrameworkCore.Test/Repository/EntityRepositoryCustomizedMethodTes.cs
> +            Assert.True(department.Id > 0);
use assertion scope on multiple assertions

2021-10-31 13:28 UTC, ypedroo commented on test/DataQI.EntityFrameworkCore.Test/Repository/EntityRepositoryTest.cs
> +                Assert.False(ExistsCustomer(customer, useAsyncMethod));
use assertion scope on multiple assertions

2022-01-05 19:58 UTC, henrique-gouveia commented on test/DataQI.EntityFrameworkCore.Test/Repository/EntityRepositoryCustomizedMethodTes.cs
> +            Assert.True(department.Id > 0);
This is just a way to confirm that the customer has inserted into arrange part of the unit test.

2022-01-05 20:10 UTC, henrique-gouveia commented on test/DataQI.EntityFrameworkCore.Test/Repository/EntityRepositoryTest.cs
> +                Assert.False(ExistsCustomer(customer, useAsyncMethod));
This is just a way to confirm that the department has deleted.

2022-01-08 13:11 UTC, merged